name: "Install node and dependencies"
description: "Installs node and dependencies with npm ci"
inputs:
  NODE_VERSION_FILE:
    description: "Location of the .nvmrc file"
    required: true
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.NODE_VERSION_FILE }}
    - name: Install
      shell: bash
      run: npm ci
