version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

jobs:
  test_and_build:
    working_directory: ~/app
    docker:
      - image: cimg/node:22.12.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Format
          command: npm run format
      - run:
          name: Build with ts
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t gcr.io/snyk-main/code-review-exercise-node:$TAG .

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: alerts-app-sec
          trusted-branch: main
      - test_and_build
